### ISSUE TITLE
wrong link?

### ISSUE THREAD

**Issue by gabegreenberg** [VulcanJS/vulcan-home#1]
https://github.com/VulcanJS/vulcan-home/blob/aedbf422caa90ad22ef03566d5d169a59383ad3a/pages/index.js#L28

@SachaG is this a mistake? I thought it always pointed to https://github.com/VulcanJS/ but perhaps I'm mistaken.

**Comment by SachaG** [comment]
Oh yeah that's wrong, thanks!
